package com.crypto.demo.attacks;

import com.crypto.demo.util.CryptoConfig;

import java.math.BigInteger;
import java.security.*;
import java.security.interfaces.RSAPublicKey;
import java.util.List;

/**
 * ROCA VULNERABILITY DEMONSTRATION
 *
 * ROCA = Return Of Coppersmith's Attack (CVE-2017-15361)
 *
 * Background:
 *   In 2017, researchers discovered that RSA keys generated by Infineon TPM chips
 *   (used in YubiKey 4, government ID cards, HP laptops, Chromebooks, and more)
 *   had a fatal flaw: the prime factors p and q were generated using a flawed
 *   algorithm that severely restricted the space of possible primes.
 *
 *   Instead of choosing from ~2^1023 possible primes (for a 2048-bit key),
 *   the Infineon algorithm only chose from ~2^35 candidates. This made factoring
 *   the public key computationally feasible using Coppersmith's lattice method.
 *
 *   Estimated factoring costs (2017):
 *     1024-bit key: ~$40 USD on AWS
 *     2048-bit key: ~$20,000–$40,000 USD
 *     4096-bit key: Too expensive, but still weaker than it should be
 *
 * The Fingerprint Test:
 *   ROCA-vulnerable keys have a distinctive mathematical fingerprint:
 *   the public modulus N, when divided by the product of the first k primes
 *   (called a primorial), leaves a remainder that is always a power of 2.
 *
 *   Specifically, N mod M(k) = 2^a mod M(k) for some small integer a,
 *   where M(k) = 2 * 3 * 5 * 7 * 11 * ... * prime_k
 *
 *   This fingerprint does NOT require factoring the key — it can be checked
 *   in milliseconds on any public key, which is why it was so devastating.
 *
 * What this demo shows:
 *   1. Generate a standard secure RSA key — show it is NOT vulnerable
 *   2. Construct a synthetic ROCA-fingerprinted modulus — show it IS flagged
 *   3. Explain what to do if your key is vulnerable
 */
public class RocaDemo {

    static { CryptoConfig.init(); }

    /**
     * The first 39 primes — used to compute primorials for the ROCA fingerprint check.
     * The original ROCA paper uses primes up to the 39th prime (167) for 512-2048 bit keys.
     */
    private static final int[] PRIMES = {
            2, 3, 5, 7, 11, 13, 17, 19, 23, 29,
            31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
            73, 79, 83, 89, 97, 101, 103, 107, 109, 113,
            127, 131, 137, 139, 149, 151, 157, 163, 167
    };

    // ----------------------------------------------------------------
    // ROCA FINGERPRINT CHECK
    // ----------------------------------------------------------------

    /**
     * Tests whether an RSA public key is ROCA-vulnerable.
     *
     * Algorithm (simplified from the original paper):
     *   For each prefix of the primes list:
     *     1. Compute M = product of those primes (the primorial)
     *     2. Compute r = N mod M
     *     3. Check if r is a power of 2 modulo M
     *     4. If yes for enough primorials → key is ROCA-vulnerable
     *
     * A real production check (e.g. keychest.net) uses all 39 primes.
     * This implementation uses the first 10 for demo speed, which catches
     * the fingerprint pattern clearly.
     *
     * @param publicKey RSA public key to test
     * @return RocaResult with vulnerable flag and explanation
     */
    public RocaResult checkVulnerability(RSAPublicKey publicKey) {
        BigInteger n = publicKey.getModulus();
        int keyBits  = n.bitLength();

        // Determine how many primorials to check based on key size
        // Larger keys need more primorials for a reliable fingerprint
        int primorialsToCheck = keyBits >= 2048 ? 10 : 7;

        int fingerprints = 0;
        BigInteger primorial = BigInteger.ONE;

        StringBuilder detail = new StringBuilder();

        for (int i = 0; i < primorialsToCheck; i++) {
            primorial = primorial.multiply(BigInteger.valueOf(PRIMES[i]));
            BigInteger r = n.mod(primorial);

            // Check if r is a power of 2 mod the primorial
            boolean isPowerOf2 = isPowerOfTwoMod(r, primorial);
            if (isPowerOf2) fingerprints++;

            detail.append(String.format(
                    "  Primorial(%d primes) = %s, N mod M = %s, Power-of-2? %s%n",
                    i + 1,
                    primorial.toString().length() > 12
                            ? primorial.toString().substring(0, 12) + "..."
                            : primorial,
                    r.toString().length() > 10
                            ? r.toString().substring(0, 10) + "..."
                            : r,
                    isPowerOf2 ? "YES ⚠" : "no"
            ));
        }

        // If most primorials show the fingerprint → vulnerable
        boolean vulnerable = fingerprints >= (primorialsToCheck * 2 / 3);

        return new RocaResult(
                vulnerable,
                keyBits,
                fingerprints,
                primorialsToCheck,
                detail.toString()
        );
    }

    /**
     * Checks if value is a power of 2 modulo modulus.
     * i.e. does there exist k such that 2^k ≡ value (mod modulus)?
     */
    private boolean isPowerOfTwoMod(BigInteger value, BigInteger modulus) {
        if (value.equals(BigInteger.ZERO)) return false;
        BigInteger power = BigInteger.ONE;
        // Check 2^0 through 2^(bit length of modulus)
        for (int k = 0; k < modulus.bitLength() + 1; k++) {
            if (power.equals(value)) return true;
            power = power.multiply(BigInteger.TWO).mod(modulus);
            if (power.equals(BigInteger.ONE) && k > 0) break; // cycled
        }
        return false;
    }

    // ----------------------------------------------------------------
    // MAIN DEMO
    // ----------------------------------------------------------------

    public static void main(String[] args) throws Exception {
        CryptoConfig.init();
        RocaDemo demo = new RocaDemo();

        System.out.println("╔══════════════════════════════════════════════════╗");
        System.out.println("║       ROCA VULNERABILITY DEMO (CVE-2017-15361)   ║");
        System.out.println("║  COSC370 - Lei Tapungot                          ║");
        System.out.println("╚══════════════════════════════════════════════════╝\n");

        System.out.println("ROCA = Return Of Coppersmith's Attack");
        System.out.println("Affected: Infineon TPM chips in YubiKey 4, HP laptops,");
        System.out.println("          government ID cards, Chromebooks (2012-2017)\n");

        // ── Part 1: Check a secure key ────────────────────────────────
        System.out.println("── PART 1: Standard RSA Key (Java SecureRandom) ──");
        KeyPairGenerator kpg = KeyPairGenerator.getInstance("RSA");
        kpg.initialize(2048, new SecureRandom());
        KeyPair secureKeyPair = kpg.generateKeyPair();
        RSAPublicKey secureKey = (RSAPublicKey) secureKeyPair.getPublic();

        System.out.println("Generated RSA-2048 key with Java SecureRandom.");
        System.out.println("Key modulus (first 40 hex chars): "
                + secureKey.getModulus().toString(16).substring(0, 40) + "...\n");

        System.out.println("Running ROCA fingerprint check...");
        RocaResult secureResult = demo.checkVulnerability(secureKey);
        secureResult.print();

        // ── Part 2: Construct a synthetic vulnerable-fingerprint modulus ──
        System.out.println("\n── PART 2: Synthetic ROCA-Fingerprinted Modulus ──");
        System.out.println("Constructing a modulus with ROCA fingerprint pattern...");
        System.out.println("(Simulating what an Infineon TPM would produce)\n");

        // Build a synthetic N with the ROCA fingerprint:
        // N ≡ 2^a (mod M) for the first several primorials
        // We construct this by starting from a primorial-aligned base
        BigInteger primorial = BigInteger.TWO;
        for (int i = 1; i < 8; i++) {
            primorial = primorial.multiply(BigInteger.valueOf(PRIMES[i]));
        }
        // N = primorial * k + 2^3 for some k (artificially fingerprinted)
        BigInteger syntheticN = primorial.multiply(BigInteger.valueOf(999983))
                .add(BigInteger.valueOf(8)); // 8 = 2^3

        // Wrap it as a fake RSA public key for the check
        // (We can't make a real key this way — this just demonstrates the fingerprint)
        System.out.println("Synthetic N (first 40 chars): "
                + syntheticN.toString().substring(0, Math.min(40, syntheticN.toString().length()))
                + "...");

        // Manual fingerprint check on synthetic modulus
        System.out.println("\nRunning ROCA fingerprint check on synthetic modulus:");
        BigInteger m = BigInteger.ONE;
        int hits = 0;
        for (int i = 0; i < 8; i++) {
            m = m.multiply(BigInteger.valueOf(PRIMES[i]));
            BigInteger r = syntheticN.mod(m);
            boolean powerOf2 = demo.isPowerOfTwoMod(r, m);
            if (powerOf2) hits++;
            System.out.printf("  Primorial(%d primes): N mod M = %s, Power-of-2? %s%n",
                    i + 1,
                    r.toString().length() > 10 ? r.toString().substring(0, 10) + "..." : r,
                    powerOf2 ? "YES ⚠" : "no");
        }
        System.out.println("\nFingerprint hits : " + hits + " / 8");
        System.out.println("ROCA vulnerable  : " + (hits >= 5 ? "YES ⚠" : "NO ✓"));

        // ── Part 3: Impact & Remediation ─────────────────────────────
        System.out.println("\n── PART 3: Impact & Remediation ─────────────────");
        System.out.println("Impact:");
        System.out.println("  ~750,000 Estonian e-ID cards revoked (Oct 2017)");
        System.out.println("  Infineon firmware update pushed to millions of devices");
        System.out.println("  YubiKey 4 series required replacement");
        System.out.println("  Slovak national ID cards suspended");
        System.out.println("  GitHub, Google, Apple all scanned for affected keys\n");

        System.out.println("Factoring cost (2017 AWS spot prices):");
        System.out.println("  512-bit  : < $0.10");
        System.out.println("  1024-bit : ~$40");
        System.out.println("  2048-bit : ~$20,000 - $40,000");
        System.out.println("  4096-bit : ~$10,000,000,000 (still weaker than expected)\n");

        System.out.println("Remediation:");
        System.out.println("  1. Check your keys: keychest.net/roca or this demo");
        System.out.println("  2. Regenerate any flagged keys using secure RNG");
        System.out.println("  3. Update Infineon TPM firmware");
        System.out.println("  4. Our project uses Java SecureRandom — NOT vulnerable\n");

        System.out.println("── SUMMARY ───────────────────────────────────────");
        System.out.println("Standard Java RSA key : NOT vulnerable ✓");
        System.out.println("Infineon TPM keys     : VULNERABLE (if not patched)");
        System.out.println("Detection             : Milliseconds, no factoring needed");
        System.out.println("Lesson                : Key generation algorithm matters");
        System.out.println("                        as much as key size.");
    }

    // ----------------------------------------------------------------
    // RESULT RECORD
    // ----------------------------------------------------------------

    public record RocaResult(
            boolean vulnerable,
            int keyBits,
            int fingerprintHits,
            int primorialsChecked,
            String detail
    ) {
        public void print() {
            System.out.println("Key size          : " + keyBits + " bits");
            System.out.println("Primorials checked: " + primorialsChecked);
            System.out.println("Fingerprint hits  : " + fingerprintHits
                    + " / " + primorialsChecked);
            System.out.println(detail);
            System.out.println("ROCA vulnerable   : "
                    + (vulnerable ? "YES ⚠  — regenerate this key immediately!"
                    : "NO  ✓  — key was generated securely"));
        }
    }
}